
cc_library(
    name = "geometry",
    hdrs = ["geometry.hpp"],
    srcs = ["geometry.cpp",
    ],
    deps = [
	    "@com_github_eigen_eigen//:eigen",
        "@boost//:polygon",
        "@boost//:geometry",
        "@bark_project//bark:include",
    ],
    visibility = ["//visibility:public"]
)
