cc_library(
    name = "reference_trajectory_generator",
    srcs = [
        "reference_trajectory_generator.cpp",
    ],
    hdrs = [
        "reference_trajectory_generator.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@bark_project//bark:include",
        "@com_github_glog_glog//:glog",
        "//common/math:math"
    ],
)