
cc_library(
    name = "dynamic_conversion",
    hdrs = ["dynamic_conversion.hpp"],
    deps = [
	    "@com_github_eigen_eigen//:eigen",
        "@bark_project//bark:include",
    ],
    visibility = ["//visibility:public"]
)
